-- liquibase formatted sql

-- changeset yuliya:1
CREATE TABLE status(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statusPostalItems VARCHAR(200)
)
-- changeset yuliya:2
CREATE TABLE post_office(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index INTEGER,
    name VARCHAR(200),
    address VARCHAR(200)
)

-- changeset yuliya:3
CREATE TABLE postal_items(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200),
    type VARCHAR(50),
    indexRecipient INTEGER,
    addressRecipient VARCHAR(200)
)
-- changeset yuliya:4
CREATE TABLE transactions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time            TIME WITH TIME ZONE NOT NULL,
    post_office_id  BIGINT REFERENCES post_office (id),
    status          VARCHAR(50),
    postal_items_id BIGINT REFERENCES postal_items (id)
);
DROP TABLE status;


