-- liquibase formatted sql

-- changeset yuliya:1
CREATE TABLE status(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statusPostalItems VARCHAR(200)
)
-- changeset yuliya:2
CREATE TABLE post_office(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index INTEGER,
    name VARCHAR(200),
    address VARCHAR(200)
)

-- changeset yuliya:3
CREATE TABLE postal_items(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200),
    type VARCHAR(50),
    indexRecipient INTEGER,
    addressRecipient VARCHAR(200)
)