-- liquibase formatted sql

-- changeset Yuliya:1
CREATE TABLE post_office(
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            index INTEGER,
                            name VARCHAR(200),
                            address VARCHAR(200)
);
CREATE TABLE postal_items
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(200),
    type              VARCHAR(50),
    index_recipient   INTEGER,
    address_recipient VARCHAR(200)
);
-- changeset Yuliya:2
CREATE TABLE transactions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    post_office_id  BIGINT REFERENCES post_office (id),
    status          VARCHAR(50),
    postal_items_id BIGINT REFERENCES postal_items (id)
);

